# Generated by Django 5.1.2 on 2024-11-19 23:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='friendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFrom', models.CharField(max_length=150)),
                ('userTo', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=150)),
                ('user2', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='invites',
            fields=[
                ('userFrom', models.CharField(max_length=150)),
                ('fromSpotifyToken', models.CharField(max_length=100)),
                ('fromRefreshToken', models.CharField(max_length=100)),
                ('userTo', models.CharField(max_length=150)),
                ('time', models.CharField(choices=[('long_term', 'long_term'), ('medium_term', 'medium_term'), ('short_term', 'short_term')], max_length=15)),
                ('message', models.CharField(max_length=150)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('spotifytoken', models.CharField(max_length=100)),
                ('refreshtoken', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='wraps',
            fields=[
                ('wrap1', models.JSONField()),
                ('wrap2', models.JSONField()),
                ('duowrap', models.JSONField()),
                ('isDuo', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user1', models.CharField(max_length=150)),
                ('user2', models.CharField(max_length=150)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imageNum', models.IntegerField()),
                ('image', models.CharField(max_length=150)),
            ],
        ),
    ]
