# Generated by Django 5.1 on 2024-11-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotifywrapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifyuser",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="dark",
                max_length=10,
            ),
        ),
    ]
