# Generated by Django 5.1.1 on 2024-11-26 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapp', '0002_spotifyuser_theme_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyuser',
            name='theme_preference',
        ),
    ]
