# Generated by Django 5.1.1 on 2024-11-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapp', '0003_remove_spotifyuser_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='wraps',
            name='duration',
            field=models.CharField(choices=[('long_term', 'long_term'), ('medium_term', 'medium_term'), ('short_term', 'short_term')], default='long_term', max_length=15),
        ),
    ]
