# Generated by Django 5.1.1 on 2024-11-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifywrapp', '0004_wraps_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wraps',
            name='duration',
            field=models.CharField(default='', max_length=30),
        ),
    ]
