# Generated by Django 5.1.2 on 2024-12-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotifywrapp", "0007_remove_spotifyuser_theme_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifyuser",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="dark",
                max_length=10,
            ),
        ),
    ]
